### ISSUE TITLE
Essay category does not deploy articles URL

### ISSUE THREAD

**Issue by alesdonoso** [JaeYeopHan/gatsby-starter-bee#144]
## Description

Hi!

I'm having a serious issue when trying to access the "/assets/" category of articles after deploying. Everything works as expected except the article related to that category.

The URL of my blog is [https://alesdonoso.com/blog/](https://alesdonoso.com/blog/)

When accessing the route of the **What I’ve learned in the earlier months of a Startup — 15 tips.**, it prints a `Page Not Found`
![image](https://user-images.githubusercontent.com/48650098/86002703-ff148780-ba10-11ea-8a55-2fb684d4af64.png)

/development/ category works fine. 

The repository is at [https://github.com/alesdonoso/blog](https://github.com/alesdonoso/blog)

How could I fix this? Thanks in advance.

**Comment by JaeYeopHan** [comment]
Hi @alesdonoso :)

currently, 404 Not found resource

![image](https://user-images.githubusercontent.com/17924127/86072653-fbd6d580-babc-11ea-94ba-33a6e9182126.png)
![image](https://user-images.githubusercontent.com/17924127/86072659-02654d00-babd-11ea-9e5a-4090aee23d9d.png)


maybe,... because of this: https://github.com/alesdonoso/blog/commit/06bbd6078b5f0312a6039228ac58003a30e56623#diff-b9e136416b90437fa1dac910280b45fcR5

would you like to erase this and try again?

**Comment by alesdonoso** [comment]
That is a commit for gh-pages branch to deploy the blog with GitHub Pages. Why is it interfering with the /essay/ route? Thanks for help.
